server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/booster
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org.springframework.security: DEBUG